### ISSUE TITLE
npm install return ERROR due to microlink dependency

### ISSUE THREAD

**Issue by emanuelegurini** [brainrepo/gitbar-2023#35]
## My Setup
- MacBook Pro, 14" 2021
- Memory: 16 GB
- OS: MacOS Ventura 13.0.1
- Node: v18.12.1
- NPM: 8.19.2

## Problem
After cloning the project, _npm install_ does not complete his execution and the error attached is logged. 
Same problem happends when I try to run the project inside _stackblitz.com_

Problems seems coming from _@microlink/react": "^5.5.9_ dependency. 

After serveral attempts I think that I'm not able to solve this problem by myself, but, most important, I don't know if anyone else found this same problem. 

```
emanuelegurini@MBP-di-Emanuele gitbar-2023 % npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: nanoclamp@1.4.1
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"^18.2.0" from the root project
npm WARN   5 more (@astrojs/react, @microlink/react, react-dom, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^17" from nanoclamp@1.4.1
npm WARN node_modules/@microlink/react/node_modules/nanoclamp
npm WARN   nanoclamp@"~1.4.1" from @microlink/react@5.5.9
npm WARN   node_modules/@microlink/react
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17" from nanoclamp@1.4.1
npm WARN   node_modules/@microlink/react/node_modules/nanoclamp
npm WARN     nanoclamp@"~1.4.1" from @microlink/react@5.5.9
npm WARN     node_modules/@microlink/react
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /Users/emanuelegurini/Desktop/gitbar-2023/node_modules/re2
npm ERR! command failed
npm ERR! command sh -c -- install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild
npm ERR! Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-108.br ...
npm ERR! Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-108.gz ...
npm ERR! Building locally ...
npm ERR! 
npm ERR! > re2@1.17.7 rebuild /Users/emanuelegurini/Desktop/gitbar-2023/node_modules/re2
npm ERR! > node-gyp rebuild
npm ERR! 
npm ERR! 
npm ERR! > re2@1.17.7 rebuild /Users/emanuelegurini/Desktop/gitbar-2023/node_modules/re2
npm ERR! > node-gyp rebuild
npm ERR! gyp WARN EACCES current user ("emanuelegurini") does not have permission to access the dev dir "/Users/emanuelegurini/Library/Caches/node-gyp/18.12.1"
npm ERR! gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/9k/2tmktgm57cl5ns3d5bqxj9rh0000gn/T/.node-gyp"
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/emanuelegurini/Desktop/gitbar-2023/node_modules/re2
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! npm ERR! code ELIFECYCLE
npm ERR! npm ERR! errno 1
npm ERR! npm ERR! re2@1.17.7 rebuild: `node-gyp rebuild`
npm ERR! npm ERR! Exit status 1
npm ERR! npm ERR! 
npm ERR! npm ERR! Failed at the re2@1.17.7 rebuild script.
npm ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/emanuelegurini/.npm/_logs/2022-11-20T18_48_22_749Z-debug.log
npm ERR! node:internal/process/promises:288
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR! 
npm ERR! [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
npm ERR!   code: 'ERR_UNHANDLED_REJECTION'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.12.1
npm ERR! gyp WARN EACCES current user ("emanuelegurini") does not have permission to access the dev dir "/Users/emanuelegurini/Library/Caches/node-gyp/18.12.1"
npm ERR! gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/9k/2tmktgm57cl5ns3d5bqxj9rh0000gn/T/.node-gyp"
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/emanuelegurini/Desktop/gitbar-2023/node_modules/re2
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! npm ERR! code ELIFECYCLE
npm ERR! npm ERR! errno 1
npm ERR! npm ERR! re2@1.17.7 rebuild: `node-gyp rebuild`
npm ERR! npm ERR! Exit status 1
npm ERR! npm ERR! 
npm ERR! npm ERR! Failed at the re2@1.17.7 rebuild script.
npm ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/emanuelegurini/.npm/_logs/2022-11-20T18_48_23_320Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/emanuelegurini/.npm/_logs/2022-11-20T18_48_08_761Z-debug-0.log
```

**Comment by brainrepo** [comment]
I think micro link is a left over. We can remove it

**Comment by emanuelegurini** [comment]
> 

Did it, but I think that now lyra is looking for _search.db.json_ file, but is not inside the project folder.

I have this error message when i try to run _npm run dev_:
` error   ENOENT: no such file or directory, open '/Users/emanuelegurini/Desktop/gitbar-2023/dist//../search.db.json'`

**Comment by brainrepo** [comment]
Try to build the application and see if the file is created

**Comment by emanuelegurini** [comment]
> Try to build the application and see if the file is created

Thanks, after building, everything works fine.
So, we don't have the search.db.json untill we create the dist version.

Would you like that I update the readme with this new instructions?

**Comment by brainrepo** [comment]
Instead documenting it could be interesting to create a seach.db.json empty file in the project root
in this case everything should work fine

**Comment by emanuelegurini** [comment]
Great, I'll do it, thanks for the support!
